[package]
name = "pride-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1.2"
getopt = "1.1.3"
terminal_size = "0.1.17"
